
timeout: 3600s
steps:
#terragrunt validate
- name: eu.gcr.io/$PROJECT_ID/cloud-terraform
  entrypoint: /bin/bash
  args:
  - -c
  - |
    tfenv install
    tgenv install
    cd 'org/${_ENVIRONMENT}'
    terragrunt validate-all || exit 1
    
# terragrunt plan
- name: eu.gcr.io/$PROJECT_ID/cloud-terraform
  entrypoint: /bin/bash
  args:
  - -c
  - |
    gcloud config set auth/impersonate_service_account ${_TF_SA_EMAIL}
    tfenv install
    tgenv install
    cd 'org/${_ENVIRONMENT}'
    terragrunt plan-all || exit 1

# terragrunt apply
- name: eu.gcr.io/$PROJECT_ID/cloud-terraform
  entrypoint: /bin/bash
  args:
  - -c
  - |
    gcloud config set auth/impersonate_service_account ${_TF_SA_EMAIL}
    tfenv install
    tgenv install
    cd 'org/${_ENVIRONMENT}'
    terragrunt apply-all --terragrunt-non-interactive || exit 1

artifacts:
  objects:
    location: 'gs://${_ARTIFACT_BUCKET_NAME}/terraform/cloudbuild/apply/$BUILD_ID'
    paths: ['cloudbuild-tg-plan-apply.yaml','cloudbuild-tg-plan.yaml']